# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'brighteyes_ffs_3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1272, 937)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.central_window = QtWidgets.QVBoxLayout()
        self.central_window.setObjectName("central_window")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.prevFCSfile_button = QtWidgets.QPushButton(self.centralwidget)
        self.prevFCSfile_button.setObjectName("prevFCSfile_button")
        self.horizontalLayout_3.addWidget(self.prevFCSfile_button)
        self.FCSfile0_button = QtWidgets.QPushButton(self.centralwidget)
        self.FCSfile0_button.setObjectName("FCSfile0_button")
        self.horizontalLayout_3.addWidget(self.FCSfile0_button)
        self.FCSfile1_button = QtWidgets.QPushButton(self.centralwidget)
        self.FCSfile1_button.setObjectName("FCSfile1_button")
        self.horizontalLayout_3.addWidget(self.FCSfile1_button)
        self.FCSfile2_button = QtWidgets.QPushButton(self.centralwidget)
        self.FCSfile2_button.setObjectName("FCSfile2_button")
        self.horizontalLayout_3.addWidget(self.FCSfile2_button)
        self.FCSfile3_button = QtWidgets.QPushButton(self.centralwidget)
        self.FCSfile3_button.setObjectName("FCSfile3_button")
        self.horizontalLayout_3.addWidget(self.FCSfile3_button)
        self.FCSfile4_button = QtWidgets.QPushButton(self.centralwidget)
        self.FCSfile4_button.setObjectName("FCSfile4_button")
        self.horizontalLayout_3.addWidget(self.FCSfile4_button)
        self.nextFCSfile_button = QtWidgets.QPushButton(self.centralwidget)
        self.nextFCSfile_button.setIconSize(QtCore.QSize(20, 20))
        self.nextFCSfile_button.setObjectName("nextFCSfile_button")
        self.horizontalLayout_3.addWidget(self.nextFCSfile_button)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.horizontalLayout_3.setStretch(2, 3)
        self.horizontalLayout_3.setStretch(3, 3)
        self.horizontalLayout_3.setStretch(4, 3)
        self.horizontalLayout_3.setStretch(5, 3)
        self.horizontalLayout_3.setStretch(6, 1)
        self.central_window.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.FCSFileName_label = QtWidgets.QLabel(self.centralwidget)
        self.FCSFileName_label.setObjectName("FCSFileName_label")
        self.gridLayout_5.addWidget(self.FCSFileName_label, 1, 0, 1, 1)
        self.FCSFolderName_label = QtWidgets.QLabel(self.centralwidget)
        self.FCSFolderName_label.setObjectName("FCSFolderName_label")
        self.gridLayout_5.addWidget(self.FCSFolderName_label, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_5)
        self.label_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.label_edit.setObjectName("label_edit")
        self.horizontalLayout_4.addWidget(self.label_edit)
        self.ycoord_edit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ycoord_edit.setFont(font)
        self.ycoord_edit.setObjectName("ycoord_edit")
        self.horizontalLayout_4.addWidget(self.ycoord_edit)
        self.xcoord_edit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.xcoord_edit.setFont(font)
        self.xcoord_edit.setObjectName("xcoord_edit")
        self.horizontalLayout_4.addWidget(self.xcoord_edit)
        self.saveLabel_button = QtWidgets.QPushButton(self.centralwidget)
        self.saveLabel_button.setObjectName("saveLabel_button")
        self.horizontalLayout_4.addWidget(self.saveLabel_button)
        self.horizontalLayout_4.setStretch(0, 10)
        self.horizontalLayout_4.setStretch(1, 3)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 1)
        self.horizontalLayout_4.setStretch(4, 1)
        self.central_window.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.central_window.addItem(spacerItem)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.central_window.addLayout(self.verticalLayout_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.correlations_treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.correlations_treeWidget.setObjectName("correlations_treeWidget")
        self.horizontalLayout_5.addWidget(self.correlations_treeWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.fingerprint_widget = MplWidgetFingerPrint(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fingerprint_widget.sizePolicy().hasHeightForWidth())
        self.fingerprint_widget.setSizePolicy(sizePolicy)
        self.fingerprint_widget.setMaximumSize(QtCore.QSize(150, 150))
        self.fingerprint_widget.setObjectName("fingerprint_widget")
        self.horizontalLayout_5.addWidget(self.fingerprint_widget)
        self.horizontalLayout_5.setStretch(0, 40)
        self.horizontalLayout_5.setStretch(2, 10)
        self.central_window.addLayout(self.horizontalLayout_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.timetrace_widget = MplWidgetLinePlot(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timetrace_widget.sizePolicy().hasHeightForWidth())
        self.timetrace_widget.setSizePolicy(sizePolicy)
        self.timetrace_widget.setBaseSize(QtCore.QSize(10, 10))
        self.timetrace_widget.setObjectName("timetrace_widget")
        self.gridLayout_6.addWidget(self.timetrace_widget, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.showElements_widget = QtWidgets.QListWidget(self.centralwidget)
        self.showElements_widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showElements_widget.sizePolicy().hasHeightForWidth())
        self.showElements_widget.setSizePolicy(sizePolicy)
        self.showElements_widget.setMinimumSize(QtCore.QSize(120, 58))
        self.showElements_widget.setMaximumSize(QtCore.QSize(120, 58))
        self.showElements_widget.setObjectName("showElements_widget")
        item = QtWidgets.QListWidgetItem()
        self.showElements_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.showElements_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.showElements_widget.addItem(item)
        self.verticalLayout_2.addWidget(self.showElements_widget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.chunk_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.chunk_spinBox.setMaximum(10000)
        self.chunk_spinBox.setObjectName("chunk_spinBox")
        self.horizontalLayout_6.addWidget(self.chunk_spinBox)
        self.chunkOn_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.chunkOn_checkBox.setShortcut("")
        self.chunkOn_checkBox.setObjectName("chunkOn_checkBox")
        self.horizontalLayout_6.addWidget(self.chunkOn_checkBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.setStretch(0, 10)
        self.verticalLayout_2.setStretch(1, 3)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 7)
        self.gridLayout_6.setColumnStretch(1, 3)
        self.central_window.addLayout(self.gridLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.showchunkscorr_dropdown = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showchunkscorr_dropdown.sizePolicy().hasHeightForWidth())
        self.showchunkscorr_dropdown.setSizePolicy(sizePolicy)
        self.showchunkscorr_dropdown.setMinimumSize(QtCore.QSize(140, 0))
        self.showchunkscorr_dropdown.setMaximumSize(QtCore.QSize(250, 16777215))
        self.showchunkscorr_dropdown.setObjectName("showchunkscorr_dropdown")
        self.showchunkscorr_dropdown.addItem("")
        self.showchunkscorr_dropdown.addItem("")
        self.verticalLayout_3.addWidget(self.showchunkscorr_dropdown)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.correlations_widget = MplWidgetCorrPlot(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correlations_widget.sizePolicy().hasHeightForWidth())
        self.correlations_widget.setSizePolicy(sizePolicy)
        self.correlations_widget.setAutoFillBackground(False)
        self.correlations_widget.setObjectName("correlations_widget")
        self.horizontalLayout_8.addWidget(self.correlations_widget)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, -1, 15, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.difflaw_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.difflaw_dropdown.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.difflaw_dropdown.sizePolicy().hasHeightForWidth())
        self.difflaw_dropdown.setSizePolicy(sizePolicy)
        self.difflaw_dropdown.setMinimumSize(QtCore.QSize(120, 0))
        self.difflaw_dropdown.setObjectName("difflaw_dropdown")
        self.difflaw_dropdown.addItem("")
        self.difflaw_dropdown.addItem("")
        self.difflaw_dropdown.addItem("")
        self.verticalLayout.addWidget(self.difflaw_dropdown)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.difflaw_widget = MplWidgetDiffLawPlot(self.centralwidget)
        self.difflaw_widget.setObjectName("difflaw_widget")
        self.horizontalLayout_10.addWidget(self.difflaw_widget)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.central_window.addLayout(self.horizontalLayout_7)
        self.central_window.setStretch(0, 1)
        self.central_window.setStretch(4, 3)
        self.central_window.setStretch(5, 3)
        self.central_window.setStretch(6, 10)
        self.gridLayout_8.addLayout(self.central_window, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1272, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCalculate = QtWidgets.QMenu(self.menubar)
        self.menuCalculate.setObjectName("menuCalculate")
        self.menuRemove = QtWidgets.QMenu(self.menubar)
        self.menuRemove.setObjectName("menuRemove")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(312, 145))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.dockWidget.setFont(font)
        self.dockWidget.setAutoFillBackground(False)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.dockWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.image_widget = MplWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_widget.sizePolicy().hasHeightForWidth())
        self.image_widget.setSizePolicy(sizePolicy)
        self.image_widget.setObjectName("image_widget")
        self.gridLayout_12.addWidget(self.image_widget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prevImage_button = QtWidgets.QPushButton(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevImage_button.sizePolicy().hasHeightForWidth())
        self.prevImage_button.setSizePolicy(sizePolicy)
        self.prevImage_button.setObjectName("prevImage_button")
        self.horizontalLayout.addWidget(self.prevImage_button)
        self.imageName_button = QtWidgets.QPushButton(self.dockWidgetContents)
        self.imageName_button.setObjectName("imageName_button")
        self.horizontalLayout.addWidget(self.imageName_button)
        self.nextImage_button = QtWidgets.QPushButton(self.dockWidgetContents)
        self.nextImage_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextImage_button.sizePolicy().hasHeightForWidth())
        self.nextImage_button.setSizePolicy(sizePolicy)
        self.nextImage_button.setIconSize(QtCore.QSize(16, 16))
        self.nextImage_button.setObjectName("nextImage_button")
        self.horizontalLayout.addWidget(self.nextImage_button)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 10)
        self.horizontalLayout.setStretch(2, 1)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.imageInfo_label = QtWidgets.QLabel(self.dockWidgetContents)
        self.imageInfo_label.setObjectName("imageInfo_label")
        self.gridLayout_3.addWidget(self.imageInfo_label, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 100)
        self.gridLayout.setRowStretch(1, 10)
        self.gridLayout.setRowStretch(2, 30)
        self.gridLayout_11.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockWidget_6 = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_6.sizePolicy().hasHeightForWidth())
        self.dockWidget_6.setSizePolicy(sizePolicy)
        self.dockWidget_6.setMinimumSize(QtCore.QSize(160, 160))
        self.dockWidget_6.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_6.setObjectName("dockWidget_6")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents_6.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents_6.setSizePolicy(sizePolicy)
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.notes_edit = QtWidgets.QPlainTextEdit(self.dockWidgetContents_6)
        self.notes_edit.setGeometry(QtCore.QRect(10, 10, 211, 191))
        self.notes_edit.setObjectName("notes_edit")
        self.dockWidget_6.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_6)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_2.sizePolicy().hasHeightForWidth())
        self.dockWidget_2.setSizePolicy(sizePolicy)
        self.dockWidget_2.setMinimumSize(QtCore.QSize(160, 93))
        self.dockWidget_2.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setAutoFillBackground(True)
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.progressBar = QtWidgets.QProgressBar(self.dockWidgetContents_2)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 0, 0, 1, 1)
        self.progressBar_label = QtWidgets.QLabel(self.dockWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_label.sizePolicy().hasHeightForWidth())
        self.progressBar_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.progressBar_label.setFont(font)
        self.progressBar_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.progressBar_label.setObjectName("progressBar_label")
        self.gridLayout_4.addWidget(self.progressBar_label, 1, 0, 2, 1)
        self.gridLayout_4.setRowStretch(0, 30)
        self.gridLayout_4.setRowStretch(1, 10)
        self.gridLayout_13.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)
        self.dockWidget_3 = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_3.sizePolicy().hasHeightForWidth())
        self.dockWidget_3.setSizePolicy(sizePolicy)
        self.dockWidget_3.setMinimumSize(QtCore.QSize(260, 160))
        self.dockWidget_3.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_3.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.dockWidgetContents_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 208, 172))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.corrs_dropdown = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.corrs_dropdown.setObjectName("corrs_dropdown")
        self.corrs_dropdown.addItem("")
        self.corrs_dropdown.addItem("")
        self.corrs_dropdown.addItem("")
        self.corrs_dropdown.addItem("")
        self.corrs_dropdown.addItem("")
        self.verticalLayout_4.addWidget(self.corrs_dropdown)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.calcCorrCurrentFile_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.calcCorrCurrentFile_button.setObjectName("calcCorrCurrentFile_button")
        self.gridLayout_7.addWidget(self.calcCorrCurrentFile_button, 4, 0, 1, 1)
        self.addToJoblist_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.addToJoblist_button.setObjectName("addToJoblist_button")
        self.gridLayout_7.addWidget(self.addToJoblist_button, 4, 1, 1, 1)
        self.precision_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.precision_label.setObjectName("precision_label")
        self.gridLayout_7.addWidget(self.precision_label, 0, 0, 1, 1)
        self.resolution_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.resolution_edit.setFont(font)
        self.resolution_edit.setObjectName("resolution_edit")
        self.gridLayout_7.addWidget(self.resolution_edit, 0, 1, 1, 1)
        self.chunkSize_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.chunkSize_label.setObjectName("chunkSize_label")
        self.gridLayout_7.addWidget(self.chunkSize_label, 1, 0, 1, 1)
        self.chunkSize_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.chunkSize_edit.setFont(font)
        self.chunkSize_edit.setObjectName("chunkSize_edit")
        self.gridLayout_7.addWidget(self.chunkSize_edit, 1, 1, 1, 1)
        self.algorithm_dropdown = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.algorithm_dropdown.setObjectName("algorithm_dropdown")
        self.algorithm_dropdown.addItem("")
        self.algorithm_dropdown.addItem("")
        self.algorithm_dropdown.addItem("")
        self.algorithm_dropdown.addItem("")
        self.gridLayout_7.addWidget(self.algorithm_dropdown, 2, 1, 1, 1)
        self.algorithm_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.algorithm_label.setObjectName("algorithm_label")
        self.gridLayout_7.addWidget(self.algorithm_label, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 3, 0, 1, 1)
        self.detector_dropdown = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.detector_dropdown.setObjectName("detector_dropdown")
        self.detector_dropdown.addItem("")
        self.detector_dropdown.addItem("")
        self.gridLayout_7.addWidget(self.detector_dropdown, 3, 1, 1, 1)
        self.gridLayout_7.setColumnStretch(0, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_7)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_3)
        self.dockWidget_4 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_4.sizePolicy().hasHeightForWidth())
        self.dockWidget_4.setSizePolicy(sizePolicy)
        self.dockWidget_4.setMinimumSize(QtCore.QSize(260, 475))
        self.dockWidget_4.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_4.setObjectName("dockWidget_4")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setMinimumSize(QtCore.QSize(0, 450))
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.dockWidgetContents_4)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 231, 487))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.fitModel_dropdown = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitModel_dropdown.sizePolicy().hasHeightForWidth())
        self.fitModel_dropdown.setSizePolicy(sizePolicy)
        self.fitModel_dropdown.setMaximumSize(QtCore.QSize(16777215, 20))
        self.fitModel_dropdown.setObjectName("fitModel_dropdown")
        self.fitModel_dropdown.addItem("")
        self.fitModel_dropdown.addItem("")
        self.fitModel_dropdown.addItem("")
        self.fitModel_dropdown.addItem("")
        self.fitModel_dropdown.addItem("")
        self.verticalLayout_8.addWidget(self.fitModel_dropdown)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setVerticalSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.fit2_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fit2_edit.setFont(font)
        self.fit2_edit.setObjectName("fit2_edit")
        self.gridLayout_9.addWidget(self.fit2_edit, 2, 1, 1, 1)
        self.fit8_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fit8_edit.setFont(font)
        self.fit8_edit.setObjectName("fit8_edit")
        self.gridLayout_9.addWidget(self.fit8_edit, 8, 1, 1, 1)
        self.fitstop_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.fitstop_label.setObjectName("fitstop_label")
        self.gridLayout_9.addWidget(self.fitstop_label, 13, 0, 1, 1)
        self.fitstart_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.fitstart_label.setObjectName("fitstart_label")
        self.gridLayout_9.addWidget(self.fitstart_label, 12, 0, 1, 1)
        self.fit5_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.fit5_checkBox.setObjectName("fit5_checkBox")
        self.gridLayout_9.addWidget(self.fit5_checkBox, 5, 0, 1, 1)
        self.fit0_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fit0_edit.setFont(font)
        self.fit0_edit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.fit0_edit.setObjectName("fit0_edit")
        self.gridLayout_9.addWidget(self.fit0_edit, 0, 1, 1, 1)
        self.fit7_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fit7_edit.setFont(font)
        self.fit7_edit.setObjectName("fit7_edit")
        self.gridLayout_9.addWidget(self.fit7_edit, 7, 1, 1, 1)
        self.overwriteFit_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.overwriteFit_button.setIconSize(QtCore.QSize(0, 0))
        self.overwriteFit_button.setObjectName("overwriteFit_button")
        self.gridLayout_9.addWidget(self.overwriteFit_button, 14, 0, 1, 1)
        self.fit1_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fit1_edit.setFont(font)
        self.fit1_edit.setObjectName("fit1_edit")
        self.gridLayout_9.addWidget(self.fit1_edit, 1, 1, 1, 1)
        self.fit7_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.fit7_checkBox.setObjectName("fit7_checkBox")
        self.gridLayout_9.addWidget(self.fit7_checkBox, 7, 0, 1, 1)
        self.fit5_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fit5_edit.setFont(font)
        self.fit5_edit.setObjectName("fit5_edit")
        self.gridLayout_9.addWidget(self.fit5_edit, 5, 1, 1, 1)
        self.newFit_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.newFit_button.setObjectName("newFit_button")
        self.gridLayout_9.addWidget(self.newFit_button, 14, 1, 1, 1)
        self.fit6_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.fit6_checkBox.setObjectName("fit6_checkBox")
        self.gridLayout_9.addWidget(self.fit6_checkBox, 6, 0, 1, 1)
        self.fit8_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.fit8_checkBox.setObjectName("fit8_checkBox")
        self.gridLayout_9.addWidget(self.fit8_checkBox, 8, 0, 1, 1)
        self.fit4_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fit4_edit.setFont(font)
        self.fit4_edit.setObjectName("fit4_edit")
        self.gridLayout_9.addWidget(self.fit4_edit, 4, 1, 1, 1)
        self.fit3_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fit3_edit.setFont(font)
        self.fit3_edit.setObjectName("fit3_edit")
        self.gridLayout_9.addWidget(self.fit3_edit, 3, 1, 1, 1)
        self.fit4_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.fit4_checkBox.setObjectName("fit4_checkBox")
        self.gridLayout_9.addWidget(self.fit4_checkBox, 4, 0, 1, 1)
        self.fit6_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fit6_edit.setFont(font)
        self.fit6_edit.setObjectName("fit6_edit")
        self.gridLayout_9.addWidget(self.fit6_edit, 6, 1, 1, 1)
        self.fit9_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fit9_edit.setFont(font)
        self.fit9_edit.setObjectName("fit9_edit")
        self.gridLayout_9.addWidget(self.fit9_edit, 9, 1, 1, 1)
        self.fit9_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.fit9_checkBox.setObjectName("fit9_checkBox")
        self.gridLayout_9.addWidget(self.fit9_checkBox, 9, 0, 1, 1)
        self.fit10_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.fit10_checkBox.setObjectName("fit10_checkBox")
        self.gridLayout_9.addWidget(self.fit10_checkBox, 10, 0, 1, 1)
        self.fit10_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fit10_edit.setFont(font)
        self.fit10_edit.setObjectName("fit10_edit")
        self.gridLayout_9.addWidget(self.fit10_edit, 10, 1, 1, 1)
        self.fit1_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.fit1_checkBox.setObjectName("fit1_checkBox")
        self.gridLayout_9.addWidget(self.fit1_checkBox, 1, 0, 1, 1)
        self.fitstart_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_4)
        self.fitstart_spinBox.setMinimum(1)
        self.fitstart_spinBox.setMaximum(999)
        self.fitstart_spinBox.setObjectName("fitstart_spinBox")
        self.gridLayout_9.addWidget(self.fitstart_spinBox, 12, 1, 1, 1)
        self.fitstop_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_4)
        self.fitstop_spinBox.setMinimum(1)
        self.fitstop_spinBox.setMaximum(10000)
        self.fitstop_spinBox.setProperty("value", 100)
        self.fitstop_spinBox.setObjectName("fitstop_spinBox")
        self.gridLayout_9.addWidget(self.fitstop_spinBox, 13, 1, 1, 1)
        self.fit0_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.fit0_checkBox.setObjectName("fit0_checkBox")
        self.gridLayout_9.addWidget(self.fit0_checkBox, 0, 0, 1, 1)
        self.fit3_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.fit3_checkBox.setObjectName("fit3_checkBox")
        self.gridLayout_9.addWidget(self.fit3_checkBox, 3, 0, 1, 1)
        self.fit2_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.fit2_checkBox.setObjectName("fit2_checkBox")
        self.gridLayout_9.addWidget(self.fit2_checkBox, 2, 0, 1, 1)
        self.fitweighted_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.fitweighted_checkBox.setObjectName("fitweighted_checkBox")
        self.gridLayout_9.addWidget(self.fitweighted_checkBox, 11, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_9)
        self.dockWidget_4.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_4)
        self.dockWidget_5 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_5.setMinimumSize(QtCore.QSize(270, 230))
        self.dockWidget_5.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_5.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_5.setObjectName("dockWidget_5")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.gridLayoutWidget = QtWidgets.QWidget(self.dockWidgetContents_5)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 251, 210))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.visc_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.visc_edit.setFont(font)
        self.visc_edit.setObjectName("visc_edit")
        self.gridLayout_10.addWidget(self.visc_edit, 5, 1, 1, 1)
        self.viscosity_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.viscosity_label.setObjectName("viscosity_label")
        self.gridLayout_10.addWidget(self.viscosity_label, 5, 0, 1, 1)
        self.w0_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.w0_label.setObjectName("w0_label")
        self.gridLayout_10.addWidget(self.w0_label, 0, 0, 1, 1)
        self.D_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.D_edit.setFont(font)
        self.D_edit.setObjectName("D_edit")
        self.gridLayout_10.addWidget(self.D_edit, 2, 1, 1, 1)
        self.D_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.D_label.setObjectName("D_label")
        self.gridLayout_10.addWidget(self.D_label, 2, 0, 1, 1)
        self.w0_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.w0_edit.setFont(font)
        self.w0_edit.setObjectName("w0_edit")
        self.gridLayout_10.addWidget(self.w0_edit, 0, 1, 1, 1)
        self.T_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.T_edit.setFont(font)
        self.T_edit.setObjectName("T_edit")
        self.gridLayout_10.addWidget(self.T_edit, 4, 1, 1, 1)
        self.temperature_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.temperature_label.setObjectName("temperature_label")
        self.gridLayout_10.addWidget(self.temperature_label, 4, 0, 1, 1)
        self.keepFixed_dropdown = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.keepFixed_dropdown.setObjectName("keepFixed_dropdown")
        self.keepFixed_dropdown.addItem("")
        self.keepFixed_dropdown.addItem("")
        self.gridLayout_10.addWidget(self.keepFixed_dropdown, 3, 0, 1, 1)
        self.updateDiffLaw_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.updateDiffLaw_button.setObjectName("updateDiffLaw_button")
        self.gridLayout_10.addWidget(self.updateDiffLaw_button, 3, 1, 1, 1)
        self.calcDiameter_dropdown = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.calcDiameter_dropdown.setObjectName("calcDiameter_dropdown")
        self.calcDiameter_dropdown.addItem("")
        self.calcDiameter_dropdown.addItem("")
        self.calcDiameter_dropdown.addItem("")
        self.gridLayout_10.addWidget(self.calcDiameter_dropdown, 7, 0, 1, 1)
        self.diameter_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.diameter_label.setObjectName("diameter_label")
        self.gridLayout_10.addWidget(self.diameter_label, 6, 0, 1, 1)
        self.diameter_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.diameter_edit.setFont(font)
        self.diameter_edit.setObjectName("diameter_edit")
        self.gridLayout_10.addWidget(self.diameter_edit, 6, 1, 1, 1)
        self.updateDiffLawDiameter_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.updateDiffLawDiameter_button.setObjectName("updateDiffLawDiameter_button")
        self.gridLayout_10.addWidget(self.updateDiffLawDiameter_button, 7, 1, 1, 1)
        self.dockWidget_5.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_5)
        self.actionOpen_image = QtWidgets.QAction(MainWindow)
        self.actionOpen_image.setObjectName("actionOpen_image")
        self.actionChange_image = QtWidgets.QAction(MainWindow)
        self.actionChange_image.setObjectName("actionChange_image")
        self.actionOpen_session = QtWidgets.QAction(MainWindow)
        self.actionOpen_session.setObjectName("actionOpen_session")
        self.actionSave_session = QtWidgets.QAction(MainWindow)
        self.actionSave_session.setObjectName("actionSave_session")
        self.actionNew_session = QtWidgets.QAction(MainWindow)
        self.actionNew_session.setObjectName("actionNew_session")
        self.actionCorrelation = QtWidgets.QAction(MainWindow)
        self.actionCorrelation.setObjectName("actionCorrelation")
        self.actionAllCorrelationsCurrentFile = QtWidgets.QAction(MainWindow)
        self.actionAllCorrelationsCurrentFile.setObjectName("actionAllCorrelationsCurrentFile")
        self.actionCurrent_fit = QtWidgets.QAction(MainWindow)
        self.actionCurrent_fit.setObjectName("actionCurrent_fit")
        self.actionCurrent_correlation = QtWidgets.QAction(MainWindow)
        self.actionCurrent_correlation.setObjectName("actionCurrent_correlation")
        self.det_Genoa_Instrument_5x5 = QtWidgets.QAction(MainWindow)
        self.det_Genoa_Instrument_5x5.setCheckable(True)
        self.det_Genoa_Instrument_5x5.setChecked(True)
        self.det_Genoa_Instrument_5x5.setObjectName("det_Genoa_Instrument_5x5")
        self.det_Genoa_Instruments_7x7 = QtWidgets.QAction(MainWindow)
        self.det_Genoa_Instruments_7x7.setCheckable(True)
        self.det_Genoa_Instruments_7x7.setObjectName("det_Genoa_Instruments_7x7")
        self.det_Nikon_NSPARC = QtWidgets.QAction(MainWindow)
        self.det_Nikon_NSPARC.setCheckable(True)
        self.det_Nikon_NSPARC.setObjectName("det_Nikon_NSPARC")
        self.det_PI_Imaging_23 = QtWidgets.QAction(MainWindow)
        self.det_PI_Imaging_23.setCheckable(True)
        self.det_PI_Imaging_23.setObjectName("det_PI_Imaging_23")
        self.actionSave_session_as = QtWidgets.QAction(MainWindow)
        self.actionSave_session_as.setObjectName("actionSave_session_as")
        self.actionCurrent_FFS_file = QtWidgets.QAction(MainWindow)
        self.actionCurrent_FFS_file.setObjectName("actionCurrent_FFS_file")
        self.actionCopy_current_fit_as_data = QtWidgets.QAction(MainWindow)
        self.actionCopy_current_fit_as_data.setObjectName("actionCopy_current_fit_as_data")
        self.actionCreate_Jupyter_Notebook = QtWidgets.QAction(MainWindow)
        self.actionCreate_Jupyter_Notebook.setObjectName("actionCreate_Jupyter_Notebook")
        self.actionCopy_current_correlation = QtWidgets.QAction(MainWindow)
        self.actionCopy_current_correlation.setObjectName("actionCopy_current_correlation")
        self.actionFilter_out_bad_chunks = QtWidgets.QAction(MainWindow)
        self.actionFilter_out_bad_chunks.setObjectName("actionFilter_out_bad_chunks")
        self.actionCurrent_Image = QtWidgets.QAction(MainWindow)
        self.actionCurrent_Image.setObjectName("actionCurrent_Image")
        self.actionPlot_in_Jupyter_Notebook = QtWidgets.QAction(MainWindow)
        self.actionPlot_in_Jupyter_Notebook.setObjectName("actionPlot_in_Jupyter_Notebook")
        self.actionExport_results_to_Excel = QtWidgets.QAction(MainWindow)
        self.actionExport_results_to_Excel.setObjectName("actionExport_results_to_Excel")
        self.menuFile.addAction(self.actionOpen_image)
        self.menuFile.addAction(self.actionChange_image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_session)
        self.menuFile.addAction(self.actionSave_session)
        self.menuFile.addAction(self.actionSave_session_as)
        self.menuFile.addAction(self.actionNew_session)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_results_to_Excel)
        self.menuCalculate.addAction(self.actionCorrelation)
        self.menuCalculate.addAction(self.actionAllCorrelationsCurrentFile)
        self.menuRemove.addAction(self.actionCurrent_fit)
        self.menuRemove.addAction(self.actionCurrent_correlation)
        self.menuRemove.addAction(self.actionCurrent_FFS_file)
        self.menuRemove.addAction(self.actionCurrent_Image)
        self.menuTools.addAction(self.actionCopy_current_correlation)
        self.menuTools.addAction(self.actionCopy_current_fit_as_data)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionPlot_in_Jupyter_Notebook)
        self.menuTools.addAction(self.actionCreate_Jupyter_Notebook)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionFilter_out_bad_chunks)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCalculate.menuAction())
        self.menubar.addAction(self.menuRemove.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.showElements_widget.setCurrentRow(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.prevFCSfile_button.setText(_translate("MainWindow", "<"))
        self.FCSfile0_button.setText(_translate("MainWindow", "New file"))
        self.FCSfile1_button.setText(_translate("MainWindow", "File 2"))
        self.FCSfile2_button.setText(_translate("MainWindow", "File 3"))
        self.FCSfile3_button.setText(_translate("MainWindow", "File 4"))
        self.FCSfile4_button.setText(_translate("MainWindow", "File 5"))
        self.nextFCSfile_button.setText(_translate("MainWindow", ">"))
        self.FCSFileName_label.setText(_translate("MainWindow", "My FCS File"))
        self.FCSFolderName_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b1b1b1;\">C:\\Users\\Me\\My FCS Folder</span></p></body></html>"))
        self.label_edit.setText(_translate("MainWindow", "Label"))
        self.ycoord_edit.setText(_translate("MainWindow", "Y"))
        self.xcoord_edit.setText(_translate("MainWindow", "X"))
        self.saveLabel_button.setText(_translate("MainWindow", "ok"))
        self.correlations_treeWidget.headerItem().setText(0, _translate("MainWindow", "Correlation analysis"))
        __sortingEnabled = self.showElements_widget.isSortingEnabled()
        self.showElements_widget.setSortingEnabled(False)
        item = self.showElements_widget.item(0)
        item.setText(_translate("MainWindow", "Central"))
        item = self.showElements_widget.item(1)
        item.setText(_translate("MainWindow", "Spot-variation"))
        item = self.showElements_widget.item(2)
        item.setText(_translate("MainWindow", "All individually"))
        self.showElements_widget.setSortingEnabled(__sortingEnabled)
        self.chunkOn_checkBox.setText(_translate("MainWindow", "Chunk on"))
        self.showchunkscorr_dropdown.setItemText(0, _translate("MainWindow", "Show current chunk"))
        self.showchunkscorr_dropdown.setItemText(1, _translate("MainWindow", "Show average all active chunks"))
        self.difflaw_dropdown.setItemText(0, _translate("MainWindow", "Diffusion law"))
        self.difflaw_dropdown.setItemText(1, _translate("MainWindow", "Particle number"))
        self.difflaw_dropdown.setItemText(2, _translate("MainWindow", "Number and brightness"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuCalculate.setTitle(_translate("MainWindow", "Calculate"))
        self.menuRemove.setTitle(_translate("MainWindow", "Remove"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Image"))
        self.prevImage_button.setText(_translate("MainWindow", "<"))
        self.imageName_button.setText(_translate("MainWindow", "PushButton"))
        self.nextImage_button.setText(_translate("MainWindow", ">"))
        self.imageInfo_label.setText(_translate("MainWindow", "Image info"))
        self.dockWidget_6.setWindowTitle(_translate("MainWindow", "Notes"))
        self.dockWidget_2.setWindowTitle(_translate("MainWindow", "Status"))
        self.progressBar_label.setText(_translate("MainWindow", "Done."))
        self.dockWidget_3.setWindowTitle(_translate("MainWindow", "Calculate correlations"))
        self.corrs_dropdown.setItemText(0, _translate("MainWindow", "Spot-variation FCS"))
        self.corrs_dropdown.setItemText(1, _translate("MainWindow", "Cross-correlation spectroscopy"))
        self.corrs_dropdown.setItemText(2, _translate("MainWindow", "Pair-correlation FCS"))
        self.corrs_dropdown.setItemText(3, _translate("MainWindow", "All autocorrelations"))
        self.corrs_dropdown.setItemText(4, _translate("MainWindow", "STICS with iMSD analysis"))
        self.calcCorrCurrentFile_button.setText(_translate("MainWindow", "Calculate now"))
        self.addToJoblist_button.setText(_translate("MainWindow", "Add to joblist"))
        self.precision_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">Precision</span></p></body></html>"))
        self.resolution_edit.setText(_translate("MainWindow", "10"))
        self.chunkSize_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">Chunk size (s)</span></p></body></html>"))
        self.chunkSize_edit.setText(_translate("MainWindow", "10"))
        self.algorithm_dropdown.setItemText(0, _translate("MainWindow", "Multipletau"))
        self.algorithm_dropdown.setItemText(1, _translate("MainWindow", "Wiener-Khinchin"))
        self.algorithm_dropdown.setItemText(2, _translate("MainWindow", "TT2Corr"))
        self.algorithm_dropdown.setItemText(3, _translate("MainWindow", "PCH"))
        self.algorithm_label.setText(_translate("MainWindow", "Algorithm"))
        self.label.setText(_translate("MainWindow", "Detector"))
        self.detector_dropdown.setItemText(0, _translate("MainWindow", "Square 5x5"))
        self.detector_dropdown.setItemText(1, _translate("MainWindow", "Airyscan 32"))
        self.dockWidget_4.setWindowTitle(_translate("MainWindow", "Fit analysis"))
        self.fitModel_dropdown.setItemText(0, _translate("MainWindow", "Free diffusion 1 component"))
        self.fitModel_dropdown.setItemText(1, _translate("MainWindow", "Anomalous diffusion 1 component"))
        self.fitModel_dropdown.setItemText(2, _translate("MainWindow", "Free diffusion circular scanning"))
        self.fitModel_dropdown.setItemText(3, _translate("MainWindow", "Free diffusion 2 components"))
        self.fitModel_dropdown.setItemText(4, _translate("MainWindow", "2 components with afterpulsing"))
        self.fit2_edit.setText(_translate("MainWindow", "3,3,3"))
        self.fit8_edit.setText(_translate("MainWindow", "NaN"))
        self.fitstop_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">Stop</span></p></body></html>"))
        self.fitstart_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">Start</span></p></body></html>"))
        self.fit5_checkBox.setText(_translate("MainWindow", "None"))
        self.fit0_edit.setText(_translate("MainWindow", "1,1,1"))
        self.fit7_edit.setText(_translate("MainWindow", "NaN"))
        self.overwriteFit_button.setText(_translate("MainWindow", "Overwrite fit"))
        self.fit1_edit.setText(_translate("MainWindow", "1,1,1"))
        self.fit7_checkBox.setText(_translate("MainWindow", "None"))
        self.fit5_edit.setText(_translate("MainWindow", "NaN"))
        self.newFit_button.setText(_translate("MainWindow", "New fit"))
        self.fit6_checkBox.setText(_translate("MainWindow", "None"))
        self.fit8_checkBox.setText(_translate("MainWindow", "None"))
        self.fit4_edit.setText(_translate("MainWindow", "NaN"))
        self.fit3_edit.setText(_translate("MainWindow", "0,0,0"))
        self.fit4_checkBox.setText(_translate("MainWindow", "None"))
        self.fit6_edit.setText(_translate("MainWindow", "NaN"))
        self.fit9_edit.setText(_translate("MainWindow", "NaN"))
        self.fit9_checkBox.setText(_translate("MainWindow", "None"))
        self.fit10_checkBox.setText(_translate("MainWindow", "None"))
        self.fit10_edit.setText(_translate("MainWindow", "NaN"))
        self.fit1_checkBox.setText(_translate("MainWindow", "Tau (ms)"))
        self.fit0_checkBox.setText(_translate("MainWindow", "N"))
        self.fit3_checkBox.setText(_translate("MainWindow", "Offset"))
        self.fit2_checkBox.setText(_translate("MainWindow", "Shape parameter"))
        self.fitweighted_checkBox.setText(_translate("MainWindow", "Weighted fit"))
        self.dockWidget_5.setWindowTitle(_translate("MainWindow", "Diffusion analysis"))
        self.visc_edit.setText(_translate("MainWindow", "0.001"))
        self.viscosity_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">Viscosity (Pa.s)</span></p></body></html>"))
        self.w0_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">Beam waist (nm)</span></p></body></html>"))
        self.D_edit.setText(_translate("MainWindow", "10.0"))
        self.D_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">D (µm^2/s)</span></p></body></html>"))
        self.w0_edit.setText(_translate("MainWindow", "250, 300, 350"))
        self.T_edit.setText(_translate("MainWindow", "293"))
        self.temperature_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">Temperature (K)</span></p></body></html>"))
        self.keepFixed_dropdown.setItemText(0, _translate("MainWindow", "Keep w0 fixed"))
        self.keepFixed_dropdown.setItemText(1, _translate("MainWindow", "Keep D fixed"))
        self.updateDiffLaw_button.setText(_translate("MainWindow", "Update"))
        self.calcDiameter_dropdown.setItemText(0, _translate("MainWindow", "Calculate diameter"))
        self.calcDiameter_dropdown.setItemText(1, _translate("MainWindow", "Calculate viscosity"))
        self.calcDiameter_dropdown.setItemText(2, _translate("MainWindow", "Calculate temperature"))
        self.diameter_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">Diameter (nm)</span></p></body></html>"))
        self.diameter_edit.setText(_translate("MainWindow", "10, 10, 10"))
        self.updateDiffLawDiameter_button.setText(_translate("MainWindow", "Update"))
        self.actionOpen_image.setText(_translate("MainWindow", "Open new image"))
        self.actionOpen_image.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionChange_image.setText(_translate("MainWindow", "Change image"))
        self.actionOpen_session.setText(_translate("MainWindow", "Open session"))
        self.actionOpen_session.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_session.setText(_translate("MainWindow", "Save session"))
        self.actionSave_session.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionNew_session.setText(_translate("MainWindow", "New session"))
        self.actionNew_session.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionCorrelation.setText(_translate("MainWindow", "Correlation"))
        self.actionAllCorrelationsCurrentFile.setText(_translate("MainWindow", "All correlations in joblist"))
        self.actionCurrent_fit.setText(_translate("MainWindow", "Current fit"))
        self.actionCurrent_fit.setShortcut(_translate("MainWindow", "Del"))
        self.actionCurrent_correlation.setText(_translate("MainWindow", "Current correlation"))
        self.det_Genoa_Instrument_5x5.setText(_translate("MainWindow", "Genoa Instruments 5x5"))
        self.det_Genoa_Instruments_7x7.setText(_translate("MainWindow", "Genoa Instruments PRISM 7x7"))
        self.det_Nikon_NSPARC.setText(_translate("MainWindow", "Nikon NSPARC"))
        self.det_PI_Imaging_23.setText(_translate("MainWindow", "PI Imaging SPAD23"))
        self.actionSave_session_as.setText(_translate("MainWindow", "Save session as..."))
        self.actionSave_session_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionCurrent_FFS_file.setText(_translate("MainWindow", "Current FFS file"))
        self.actionCopy_current_fit_as_data.setText(_translate("MainWindow", "Copy current fit as data"))
        self.actionCreate_Jupyter_Notebook.setText(_translate("MainWindow", "Create Jupyter Notebook"))
        self.actionCopy_current_correlation.setText(_translate("MainWindow", "Copy current correlation"))
        self.actionCopy_current_correlation.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionFilter_out_bad_chunks.setText(_translate("MainWindow", "Filter out bad chunks"))
        self.actionFilter_out_bad_chunks.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionCurrent_Image.setText(_translate("MainWindow", "Current Image"))
        self.actionPlot_in_Jupyter_Notebook.setText(_translate("MainWindow", "Plot in Jupyter Notebook"))
        self.actionExport_results_to_Excel.setText(_translate("MainWindow", "Export results to Excel"))

from mplwidget import MplWidget
from mplwidgetcorrplot import MplWidgetCorrPlot
from mplwidgetdifflawplot import MplWidgetDiffLawPlot
from mplwidgetfingerprint import MplWidgetFingerPrint
from mplwidgetlineplot import MplWidgetLinePlot
